AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  comprehend-01-nlpseries-ep-3

  Sample SAM Template for comprehend-01-nlpseries-ep-3

Globals:
  Function:
    Timeout: 3

Resources:
  Comprehend01nlpseriesep3Function:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: comprehend_01_nlpseries_ep_3/
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies: ComprehendFullAccess
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/sentiment'
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  ComprehendApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sentiment/"
  Comprehend01nlpseriesep3Function:
    Description: "comprehend_01_nlpseries_ep_3 Function ARN"
    Value: !GetAtt Comprehend01nlpseriesep3Function.Arn
  Comprehend01nlpseriesep3FunctionIamRole:
    Description: "Implicit IAM Role created for comprehend_01_nlpseries_ep_3 function"
    Value: !GetAtt Comprehend01nlpseriesep3FunctionRole.Arn
